do $$
declare
  users_id_type text;
  wallpapers_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into users_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'users'
    and a.attname = 'id'
    and not a.attisdropped;

  select format_type(a.atttypid, a.atttypmod)
    into wallpapers_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'wallpapers'
    and a.attname = 'id'
    and not a.attisdropped;

  if users_id_type is null or wallpapers_id_type is null then
    raise exception 'Missing users/wallpapers schema. Run supabase/repair_schema.sql first.';
  end if;

  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'notifications'
  ) then
    execute format(
      'create table public.notifications (
        id bigint generated by default as identity primary key,
        user_id %s not null references public.users(id) on delete cascade,
        wallpaper_id %s references public.wallpapers(id) on delete set null,
        kind text not null,
        title text not null,
        body text not null,
        href text,
        read_at timestamptz,
        created_at timestamptz not null default now()
      )',
      users_id_type,
      wallpapers_id_type
    );
  end if;

  execute format(
    'alter table public.notifications add column if not exists user_id %s',
    users_id_type
  );
  execute format(
    'alter table public.notifications add column if not exists wallpaper_id %s',
    wallpapers_id_type
  );
  alter table public.notifications add column if not exists kind text;
  alter table public.notifications add column if not exists title text;
  alter table public.notifications add column if not exists body text;
  alter table public.notifications add column if not exists href text;
  alter table public.notifications add column if not exists read_at timestamptz;
  alter table public.notifications add column if not exists created_at timestamptz not null default now();

  delete from public.notifications n
  where not exists (
    select 1
    from public.users u
    where u.id = n.user_id
  );

  update public.notifications n
  set wallpaper_id = null
  where wallpaper_id is not null
    and not exists (
      select 1
      from public.wallpapers w
      where w.id = n.wallpaper_id
    );

  if not exists (
    select 1
    from pg_constraint
    where conname = 'notifications_user_id_fkey'
      and conrelid = 'public.notifications'::regclass
  ) then
    alter table public.notifications
      add constraint notifications_user_id_fkey
      foreign key (user_id) references public.users(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'notifications_wallpaper_id_fkey'
      and conrelid = 'public.notifications'::regclass
  ) then
    alter table public.notifications
      add constraint notifications_wallpaper_id_fkey
      foreign key (wallpaper_id) references public.wallpapers(id) on delete set null;
  end if;
end
$$;

create index if not exists notifications_user_id_created_at_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_id_read_at_idx
  on public.notifications (user_id, read_at, created_at desc);

create index if not exists notifications_wallpaper_id_idx
  on public.notifications (wallpaper_id);

alter table if exists public.notifications enable row level security;
