do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
      and t.typname = 'wallpaper_report_status'
  ) then
    create type public.wallpaper_report_status as enum (
      'pending',
      'reviewing',
      'resolved',
      'dismissed'
    );
  end if;
end
$$;

do $$
declare
  users_id_type text;
  wallpapers_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into users_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'users'
    and a.attname = 'id'
    and not a.attisdropped;

  select format_type(a.atttypid, a.atttypmod)
    into wallpapers_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'wallpapers'
    and a.attname = 'id'
    and not a.attisdropped;

  if users_id_type is null or wallpapers_id_type is null then
    raise exception 'Missing users/wallpapers schema. Run supabase/repair_schema.sql first.';
  end if;

  alter table public.wallpapers
    add column if not exists license_confirmed_at timestamptz;
  alter table public.wallpapers
    add column if not exists license_version text;
  alter table public.wallpapers
    add column if not exists reports_count integer not null default 0;
  alter table public.wallpapers
    add column if not exists last_reported_at timestamptz;

  update public.wallpapers
  set license_confirmed_at = coalesce(license_confirmed_at, created_at),
      license_version = coalesce(nullif(trim(license_version), ''), '2026-04')
  where status = 'published';

  update public.wallpapers
  set license_version = coalesce(nullif(trim(license_version), ''), '2026-04')
  where license_version is null
     or trim(license_version) = '';

  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'wallpaper_reports'
  ) then
    execute format(
      'create table public.wallpaper_reports (
        id bigint generated by default as identity primary key,
        wallpaper_id %s not null references public.wallpapers(id) on delete cascade,
        reporter_user_id %s references public.users(id) on delete set null,
        reporter_email text,
        reporter_ip text,
        reason text not null,
        details text,
        status public.wallpaper_report_status not null default ''pending'',
        created_at timestamptz not null default now(),
        reviewed_at timestamptz,
        review_note text
      )',
      wallpapers_id_type,
      users_id_type
    );
  end if;

  execute format(
    'alter table public.wallpaper_reports add column if not exists wallpaper_id %s',
    wallpapers_id_type
  );
  execute format(
    'alter table public.wallpaper_reports add column if not exists reporter_user_id %s',
    users_id_type
  );
  alter table public.wallpaper_reports
    add column if not exists reporter_email text;
  alter table public.wallpaper_reports
    add column if not exists reporter_ip text;
  alter table public.wallpaper_reports
    add column if not exists reason text;
  alter table public.wallpaper_reports
    add column if not exists details text;
  alter table public.wallpaper_reports
    add column if not exists status public.wallpaper_report_status not null default 'pending';
  alter table public.wallpaper_reports
    add column if not exists created_at timestamptz not null default now();
  alter table public.wallpaper_reports
    add column if not exists reviewed_at timestamptz;
  alter table public.wallpaper_reports
    add column if not exists review_note text;

  delete from public.wallpaper_reports wr
  where not exists (
    select 1
    from public.wallpapers w
    where w.id = wr.wallpaper_id
  );

  update public.wallpaper_reports wr
  set reporter_user_id = null
  where reporter_user_id is not null
    and not exists (
      select 1
      from public.users u
      where u.id = wr.reporter_user_id
    );
end
$$;

create index if not exists wallpaper_reports_wallpaper_id_created_at_idx
  on public.wallpaper_reports (wallpaper_id, created_at desc);

create index if not exists wallpaper_reports_status_created_at_idx
  on public.wallpaper_reports (status, created_at desc);

create index if not exists wallpaper_reports_reporter_user_id_idx
  on public.wallpaper_reports (reporter_user_id);

update public.wallpapers w
set reports_count = report_totals.total_count,
    last_reported_at = report_totals.last_reported_at
from (
  select
    wallpaper_id,
    count(*)::integer as total_count,
    max(created_at) as last_reported_at
  from public.wallpaper_reports
  group by wallpaper_id
) as report_totals
where w.id = report_totals.wallpaper_id;

update public.wallpapers
set reports_count = 0
where reports_count is null;

alter table if exists public.wallpaper_reports enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'wallpaper_reports_wallpaper_id_fkey'
      and conrelid = 'public.wallpaper_reports'::regclass
  ) then
    alter table public.wallpaper_reports
      add constraint wallpaper_reports_wallpaper_id_fkey
      foreign key (wallpaper_id) references public.wallpapers(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'wallpaper_reports_reporter_user_id_fkey'
      and conrelid = 'public.wallpaper_reports'::regclass
  ) then
    alter table public.wallpaper_reports
      add constraint wallpaper_reports_reporter_user_id_fkey
      foreign key (reporter_user_id) references public.users(id) on delete set null;
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'wallpaper_reports'
      and policyname = 'Wallpaper reports can be submitted'
  ) then
    create policy "Wallpaper reports can be submitted"
      on public.wallpaper_reports
      for insert
      with check (true);
  end if;
end
$$;
