create extension if not exists pgcrypto;

do $$
declare
  wallpapers_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into wallpapers_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'wallpapers'
    and a.attname = 'id'
    and not a.attisdropped;

  if wallpapers_id_type is null then
    raise exception 'Missing public.wallpapers.id. Run supabase/repair_schema.sql first.';
  end if;

  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'wallpaper_favorites'
  ) then
    execute format(
      'create table public.wallpaper_favorites (
        id bigint generated by default as identity primary key,
        wallpaper_id %s not null references public.wallpapers(id) on delete cascade,
        guest_session_id text not null,
        created_at timestamptz not null default now(),
        unique (wallpaper_id, guest_session_id)
      )',
      wallpapers_id_type
    );
  end if;

  execute format(
    'alter table public.wallpaper_favorites add column if not exists wallpaper_id %s',
    wallpapers_id_type
  );
  alter table public.wallpaper_favorites add column if not exists guest_session_id text;
  alter table public.wallpaper_favorites add column if not exists created_at timestamptz not null default now();

  create unique index if not exists wallpaper_favorites_wallpaper_session_key
    on public.wallpaper_favorites (wallpaper_id, guest_session_id);
  create index if not exists wallpaper_favorites_wallpaper_id_idx
    on public.wallpaper_favorites (wallpaper_id);
  create index if not exists wallpaper_favorites_guest_session_id_idx
    on public.wallpaper_favorites (guest_session_id);

  delete from public.wallpaper_favorites wf
  where not exists (
    select 1
    from public.wallpapers w
    where w.id = wf.wallpaper_id
  );

  if not exists (
    select 1
    from pg_constraint
    where conname = 'wallpaper_favorites_wallpaper_id_fkey'
      and conrelid = 'public.wallpaper_favorites'::regclass
  ) then
    execute 'alter table public.wallpaper_favorites add constraint wallpaper_favorites_wallpaper_id_fkey foreign key (wallpaper_id) references public.wallpapers(id) on delete cascade';
  end if;
end
$$;

create or replace function public.increment_wallpaper_downloads(p_identifier text)
returns table (
  wallpaper_id text,
  downloads_count integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.wallpapers w
  set downloads_count = coalesce(w.downloads_count, 0) + 1
  where w.id in (
    select w2.id
    from public.wallpapers w2
    where w2.slug = p_identifier
       or w2.id::text = p_identifier
    order by case when w2.slug = p_identifier then 0 else 1 end
    limit 1
  )
  returning w.id::text, w.downloads_count;
end;
$$;

create or replace function public.get_wallpaper_favorite_state(
  p_identifier text,
  p_guest_session_id text default null
)
returns table (
  wallpaper_id text,
  likes_count integer,
  is_favorited boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    w.id::text as wallpaper_id,
    coalesce(w.likes_count, 0) as likes_count,
    case
      when coalesce(nullif(trim(p_guest_session_id), ''), '') = '' then false
      else exists (
        select 1
        from public.wallpaper_favorites f
        where f.wallpaper_id = w.id
          and f.guest_session_id = p_guest_session_id
      )
    end as is_favorited
  from public.wallpapers w
  where w.slug = p_identifier
     or w.id::text = p_identifier
  order by case when w.slug = p_identifier then 0 else 1 end
  limit 1;
$$;

create or replace function public.toggle_wallpaper_favorite(
  p_identifier text,
  p_guest_session_id text
)
returns table (
  wallpaper_id text,
  likes_count integer,
  is_favorited boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_wallpaper_id text;
  affected_rows integer := 0;
begin
  if coalesce(nullif(trim(p_guest_session_id), ''), '') = '' then
    raise exception 'Guest session id is required.';
  end if;

  select w.id::text
    into target_wallpaper_id
  from public.wallpapers w
  where w.slug = p_identifier
     or w.id::text = p_identifier
  order by case when w.slug = p_identifier then 0 else 1 end
  limit 1;

  if target_wallpaper_id is null then
    return;
  end if;

  insert into public.wallpaper_favorites (wallpaper_id, guest_session_id)
  select w.id, p_guest_session_id
  from public.wallpapers w
  where w.id::text = target_wallpaper_id
  on conflict (wallpaper_id, guest_session_id) do nothing;

  get diagnostics affected_rows = row_count;

  if affected_rows > 0 then
    update public.wallpapers w
    set likes_count = coalesce(w.likes_count, 0) + 1
    where w.id::text = target_wallpaper_id;
  else
    delete from public.wallpaper_favorites f
    using public.wallpapers w
    where f.wallpaper_id = w.id
      and w.id::text = target_wallpaper_id
      and f.guest_session_id = p_guest_session_id;

    update public.wallpapers w
    set likes_count = greatest(coalesce(w.likes_count, 0) - 1, 0)
    where w.id::text = target_wallpaper_id;
  end if;

  return query
  select
    w.id::text as wallpaper_id,
    coalesce(w.likes_count, 0) as likes_count,
    exists (
      select 1
      from public.wallpaper_favorites f
      where f.wallpaper_id = w.id
        and f.guest_session_id = p_guest_session_id
    ) as is_favorited
  from public.wallpapers w
  where w.id::text = target_wallpaper_id
  limit 1;
end;
$$;

alter table if exists public.wallpaper_favorites enable row level security;
