create extension if not exists pgcrypto;

do $$
declare
  users_id_type text;
  wallpapers_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into users_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'users'
    and a.attname = 'id'
    and not a.attisdropped;

  select format_type(a.atttypid, a.atttypmod)
    into wallpapers_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'wallpapers'
    and a.attname = 'id'
    and not a.attisdropped;

  if users_id_type is null or wallpapers_id_type is null then
    raise exception 'Missing users/wallpapers schema. Run supabase/repair_schema.sql first.';
  end if;

  create table if not exists public.sessions (
    id uuid primary key default gen_random_uuid(),
    email text not null,
    token_hash text not null unique,
    redirect_to text,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now()
  );

  alter table public.sessions add column if not exists email text;
  alter table public.sessions add column if not exists token_hash text;
  alter table public.sessions add column if not exists redirect_to text;
  alter table public.sessions add column if not exists expires_at timestamptz;
  alter table public.sessions add column if not exists used_at timestamptz;
  alter table public.sessions add column if not exists created_at timestamptz not null default now();

  create unique index if not exists sessions_token_hash_key
    on public.sessions (token_hash);
  create index if not exists sessions_expires_at_idx
    on public.sessions (expires_at desc);

  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'likes'
  ) then
    execute format(
      'create table public.likes (
        user_id %s not null references public.users(id) on delete cascade,
        wallpaper_id %s not null references public.wallpapers(id) on delete cascade,
        created_at timestamptz not null default now(),
        primary key (user_id, wallpaper_id)
      )',
      users_id_type,
      wallpapers_id_type
    );
  end if;

  execute format('alter table public.likes add column if not exists user_id %s', users_id_type);
  execute format('alter table public.likes add column if not exists wallpaper_id %s', wallpapers_id_type);
  alter table public.likes add column if not exists created_at timestamptz not null default now();

  create index if not exists likes_wallpaper_id_idx
    on public.likes (wallpaper_id);

  delete from public.likes l
  where not exists (
    select 1
    from public.users u
    where u.id = l.user_id
  )
  or not exists (
    select 1
    from public.wallpapers w
    where w.id = l.wallpaper_id
  );

  if not exists (
    select 1
    from pg_constraint
    where conname = 'likes_user_id_fkey'
      and conrelid = 'public.likes'::regclass
  ) then
    execute 'alter table public.likes add constraint likes_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade';
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'likes_wallpaper_id_fkey'
      and conrelid = 'public.likes'::regclass
  ) then
    execute 'alter table public.likes add constraint likes_wallpaper_id_fkey foreign key (wallpaper_id) references public.wallpapers(id) on delete cascade';
  end if;

  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'downloads'
  ) then
    execute format(
      'create table public.downloads (
        id bigint generated by default as identity primary key,
        user_id %s not null references public.users(id) on delete cascade,
        wallpaper_id %s not null references public.wallpapers(id) on delete cascade,
        variant public.wallpaper_variant,
        downloaded_at timestamptz not null default now()
      )',
      users_id_type,
      wallpapers_id_type
    );
  end if;

  execute format('alter table public.downloads add column if not exists user_id %s', users_id_type);
  execute format('alter table public.downloads add column if not exists wallpaper_id %s', wallpapers_id_type);
  alter table public.downloads add column if not exists variant public.wallpaper_variant;
  alter table public.downloads add column if not exists downloaded_at timestamptz not null default now();

  create index if not exists downloads_wallpaper_id_idx
    on public.downloads (wallpaper_id);
  create index if not exists downloads_user_id_downloaded_at_idx
    on public.downloads (user_id, downloaded_at desc);

  delete from public.downloads d
  where not exists (
    select 1
    from public.users u
    where u.id = d.user_id
  )
  or not exists (
    select 1
    from public.wallpapers w
    where w.id = d.wallpaper_id
  );

  if not exists (
    select 1
    from pg_constraint
    where conname = 'downloads_user_id_fkey'
      and conrelid = 'public.downloads'::regclass
  ) then
    execute 'alter table public.downloads add constraint downloads_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade';
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'downloads_wallpaper_id_fkey'
      and conrelid = 'public.downloads'::regclass
  ) then
    execute 'alter table public.downloads add constraint downloads_wallpaper_id_fkey foreign key (wallpaper_id) references public.wallpapers(id) on delete cascade';
  end if;

  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'collections'
  ) then
    execute format(
      'create table public.collections (
        id bigint generated by default as identity primary key,
        user_id %s not null references public.users(id) on delete cascade,
        name text not null,
        is_public boolean not null default false,
        created_at timestamptz not null default now()
      )',
      users_id_type
    );
  end if;

  execute format('alter table public.collections add column if not exists user_id %s', users_id_type);
  alter table public.collections add column if not exists name text;
  alter table public.collections add column if not exists is_public boolean not null default false;
  alter table public.collections add column if not exists created_at timestamptz not null default now();

  create unique index if not exists collections_user_id_name_key
    on public.collections (user_id, name);
  create index if not exists collections_user_id_idx
    on public.collections (user_id);

  delete from public.collections c
  where not exists (
    select 1
    from public.users u
    where u.id = c.user_id
  );

  if not exists (
    select 1
    from pg_constraint
    where conname = 'collections_user_id_fkey'
      and conrelid = 'public.collections'::regclass
  ) then
    execute 'alter table public.collections add constraint collections_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade';
  end if;

  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'collection_items'
  ) then
    execute format(
      'create table public.collection_items (
        collection_id bigint not null references public.collections(id) on delete cascade,
        wallpaper_id %s not null references public.wallpapers(id) on delete cascade,
        added_at timestamptz not null default now(),
        primary key (collection_id, wallpaper_id)
      )',
      wallpapers_id_type
    );
  end if;

  alter table public.collection_items add column if not exists collection_id bigint;
  execute format('alter table public.collection_items add column if not exists wallpaper_id %s', wallpapers_id_type);
  alter table public.collection_items add column if not exists added_at timestamptz not null default now();

  create index if not exists collection_items_wallpaper_id_idx
    on public.collection_items (wallpaper_id);

  delete from public.collection_items ci
  where not exists (
    select 1
    from public.collections c
    where c.id = ci.collection_id
  )
  or not exists (
    select 1
    from public.wallpapers w
    where w.id = ci.wallpaper_id
  );

  if not exists (
    select 1
    from pg_constraint
    where conname = 'collection_items_collection_id_fkey'
      and conrelid = 'public.collection_items'::regclass
  ) then
    alter table public.collection_items
      add constraint collection_items_collection_id_fkey
      foreign key (collection_id) references public.collections(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'collection_items_wallpaper_id_fkey'
      and conrelid = 'public.collection_items'::regclass
  ) then
    execute 'alter table public.collection_items add constraint collection_items_wallpaper_id_fkey foreign key (wallpaper_id) references public.wallpapers(id) on delete cascade';
  end if;
end
$$;

alter table if exists public.sessions enable row level security;
alter table if exists public.likes enable row level security;
alter table if exists public.downloads enable row level security;
alter table if exists public.collections enable row level security;
alter table if exists public.collection_items enable row level security;
